// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3StG3JuIGFZP1lOzKaBzg79k5cXiB9Fc',
    appId: '1:667229056669:web:faddfdbea0f51cb2646e74',
    messagingSenderId: '667229056669',
    projectId: 'loginregister-coffeemondo',
    authDomain: 'loginregister-coffeemondo.firebaseapp.com',
    storageBucket: 'loginregister-coffeemondo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6FD8IJMkYk0DJ-ucru9CFMx6ipDri3M8',
    appId: '1:667229056669:android:44d1e937c8298af7646e74',
    messagingSenderId: '667229056669',
    projectId: 'loginregister-coffeemondo',
    storageBucket: 'loginregister-coffeemondo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwME-aeD2IYPYxOOHCbcjSMOpTPNva2RE',
    appId: '1:667229056669:ios:82c12d84c8123051646e74',
    messagingSenderId: '667229056669',
    projectId: 'loginregister-coffeemondo',
    storageBucket: 'loginregister-coffeemondo.appspot.com',
    androidClientId: '667229056669-2gvi6e4f8a1g39f9lhh6k7a1rfc0i6sj.apps.googleusercontent.com',
    iosClientId: '667229056669-kcpm3g14bga4rkvqdh641g2q208712kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeemondo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwME-aeD2IYPYxOOHCbcjSMOpTPNva2RE',
    appId: '1:667229056669:ios:82c12d84c8123051646e74',
    messagingSenderId: '667229056669',
    projectId: 'loginregister-coffeemondo',
    storageBucket: 'loginregister-coffeemondo.appspot.com',
    androidClientId: '667229056669-2gvi6e4f8a1g39f9lhh6k7a1rfc0i6sj.apps.googleusercontent.com',
    iosClientId: '667229056669-kcpm3g14bga4rkvqdh641g2q208712kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeemondo',
  );
}
